# rpc bus allows php application and external clients to talk to rr services.
rpc:
  # enable rpc server (enabled by default)
  enable: false
  # rpc connection DSN. Supported TCP and Unix sockets.
  listen: "tcp://0.0.0.0:6001"
grpc:
  listen: "tcp://0.0.0.0:9001"
  proto: "../../proto/service.proto"
#  tls:
#    key:  "server.key"
#    cert: "server.crt"
  workers:
    command: "php worker.php"
    pool:
      numWorkers: 2
